/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f22",
        "secondary-container": "#47464a",
        "on-secondary-container": "#b7b4b8",
        "tertiary": "#c6c5cf",
        "surface-container-high": "#2a2a2c",
        "surface-dim": "#131315",
        "on-primary": "#690006",
        "background": "#131315",
        "surface-bright": "#39393b",
        "surface-variant": "#353437",
        "primary-fixed": "#ffdad6",
        "on-background": "#e5e1e4",
        "primary": "#ffb4ab",
        "primary-container": "#ff544b",
        "surface-container-lowest": "#0e0e10",
        "on-surface-variant": "#e9bcb7",
        "surface-container-low": "#1c1b1e",
        "surface": "#131315",
        "surface-container-highest": "#353437",
        "on-surface": "#e5e1e4",
        "secondary": "#c8c5ca",
        "heist-crimson": "#ff1e27",
        "heist-void": "#08080a",
      },
      fontFamily: {
        "headline-lg": ["'Bebas Neue'", "sans-serif"],
        "headline-md": ["'Bebas Neue'", "sans-serif"],
        "headline-sm": ["'Bebas Neue'", "sans-serif"],
        "display-lg": ["'Bebas Neue'", "sans-serif"],
        "body-lg": ["'Chivo'", "sans-serif"],
        "body-md": ["'Chivo'", "sans-serif"],
        "body-sm": ["'Chivo'", "sans-serif"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "code-md": ["'JetBrains Mono'", "monospace"],
        "code-lg": ["'JetBrains Mono'", "monospace"],
      },
    },
  },
  plugins: [],
}
